from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any


class ContractEntitySchema(BaseModel):
    """Pydantic model representing structured metadata extracted from a contract."""
    contract_type: str = Field(description="Type of contract, e.g., NDA, Service Agreement, Lease Agreement.")
    parties: List[str] = Field(default=[], description="List of primary legal entities or parties involved in the contract.")
    effective_date: Optional[str] = Field(None, description="The date the contract becomes active.")
    expiration_date: Optional[str] = Field(None, description="The date the contract expires or terminates.")
    contract_value: Optional[str] = Field(None, description="Monetary value of the agreement, e.g., $100,000 or N/A.")
    governing_law: Optional[str] = Field(None, description="The jurisdiction or state/country laws governing the contract.")
    indemnity_limit: Optional[str] = Field(None, description="Limits on liability or indemnity clauses.")
    termination_notice_period: Optional[str] = Field(None, description="Required notice period for termination, e.g., 30 days.")
    confidentiality_duration: Optional[str] = Field(None, description="How long confidentiality terms apply after contract termination.")

class InvoiceLineItem(BaseModel):
    description: str = Field(description="Description of the item or service.")
    quantity: Optional[float] = Field(None, description="Quantity of the item.")
    unit_price: Optional[float] = Field(None, description="Price per unit of the item.")
    amount: Optional[float] = Field(None, description="Total cost of the item line.")

class InvoiceEntitySchema(BaseModel):
    """Pydantic model representing structured metadata extracted from an invoice."""
    invoice_number: Optional[str] = Field(None, description="Unique invoice ID or invoice number.")
    supplier: Optional[str] = Field(None, description="The entity selling the goods or services.")
    buyer: Optional[str] = Field(None, description="The entity purchasing the goods or services.")
    issue_date: Optional[str] = Field(None, description="The date the invoice was issued.")
    due_date: Optional[str] = Field(None, description="The date by which payment is due.")
    line_items: List[InvoiceLineItem] = Field(default=[], description="Individual items invoiced.")
    tax_amount: Optional[float] = Field(None, description="Total tax applied to the invoice.")
    total_amount: Optional[float] = Field(None, description="Grand total amount due.")
    currency: Optional[str] = Field(default="USD", description="Currency symbol or abbreviation, e.g. USD, EUR, INR.")

class ClauseClassification(BaseModel):
    """Model representing an analysis of a single clause found in the document."""
    clause_type: str = Field(description="Type of clause, e.g., Confidentiality, Indemnification, Severability, Governing Law, Force Majeure.")
    text_segment: str = Field(description="The exact text snippet from the document matching this clause.")
    confidence: float = Field(description="Model confidence rating, between 0.0 and 1.0.")
    risk_level: str = Field(description="Assessed risk level, e.g., Low, Medium, High.")
    reasoning: str = Field(description="Detailed legal reasoning or justification for the classification and risk assessment.")


class QueryRequest(BaseModel):
    question: str = Field(..., description="The query or question to ask the document.")

class QueryResponse(BaseModel):
    answer: str = Field(..., description="The answer generated by the Q&A Agent.")
    context_chunks: List[Dict[str, Any]] = Field(default=[], description="Context snippets retrieved from ChromaDB with similarity scores.")
    agent_logs: List[str] = Field(default=[], description="Detailed step-by-step logs from the LangChain orchestrator.")

class DocumentSummaryResponse(BaseModel):
    document_id: str
    filename: str
    file_type: str
    status: str
    chunk_count: int
    summary: str
    entities: Dict[str, Any]
    clauses: List[ClauseClassification]

class DocumentListEntry(BaseModel):
    document_id: str
    filename: str
    file_type: str
    status: str
    chunk_count: int
    upload_time: str
